services:
  xray_config_aggregator:
    ports:
      - "8000:8000"
    environment:
      - LOCAL_MODE=on/off
      - FILE_PATH=config.txt
      - CONFIG_URL=https://api.github.com/.../file.txt
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - URL=/sub
      - SUB_NAME="unified links"
    volumes:
      - ${FILE_PATH}:/app/config.txt
    restart: unless-stopped

networks:
  default:
    driver: bridge
