services:
  xray_config_aggregator:
    ports:
      - "8000:8000"
    environment:
      - LOCAL_MODE=on/off
      - CONFIG_DIR=/app/configs
      - CONFIG_URL=https://api.github.com/.../file.txt
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - URL=/sub
      - CLASH_URL=/clash
      #- LOG_LEVEL=info
    volumes:
      - /path/to/configs:/app/configs
    restart: unless-stopped

networks:
  default:
    driver: bridge
